### ISSUE TITLE
Can't get auth key

### ISSUE THREAD

**Issue by Psychokiller1888** [MeteoGroup/weather-api#9]
I cannot get an auth key. I've sent a mail but did not get a response.

**Comment by Psychokiller1888** [comment]
This project is non free and commercial only. They do not respond here or their emails.

For a free and more powerfull weather API check https://openweathermap.org

**Comment by nitram509** [comment]
Hi,

I apologize for not answering quickly to your request.
Indeed, our Weather API product offers high quality forecast data for a meaningful price point.

Feel free to contact our Sales team, if you're interested in details.

Best Regards
Martin Kirst
Product Owner Weather API

**Comment by Psychokiller1888** [comment]
Which I did but they never answered, twice, over a month ago. You should take the "public" word on the repository description, if it's not free

**Comment by nitram509** [comment]
I fully agree, this is a bad thing, that I did not answer. I'm sorry for that.
We're currently changing our internal process and shifting away from my personal inbox (which I can't handle anymore) towards our professional Customer Support team.
There we have a big team working in shifts to react and reply quickly on requests.

Thank you very much for your patience. May I ask you for some more? We will have this in place by end of March. And we're happy to talk about offerings for you.

Besides that, I will keep the word public, since it doesn't necessary mean "free" as in "free beer". It also refers more to the documentation, which is public accessible.
